SET "MY_PROJECT_NAME=%1"
SET "MY_PLUGIN_DLL=%2"

SET "MY_PART_SOURCE=%~dp0\..\ksp_part"

SET "KSP_PLUGINS_DIR=%KSP_INSTALL_DIR%\Plugins"
SET "MY_PART_DIR=%KSP_INSTALL_DIR%\Parts\SubSpaceControlModule"

IF NOT EXIST "%KSP_PLUGINS_DIR%" (
	MKDIR "%KSP_PLUGINS_DIR%"
)

COPY /Y "%MY_PLUGIN_DLL%" "%KSP_PLUGINS_DIR%\%MY_PROJECT_NAME%.dll"

IF EXIST "%MY_PART_DIR%" (
	RMDIR "%MY_PART_DIR%"
)
XCOPY "%MY_PART_SOURCE%" "%MY_PART_DIR%\" /E